Repository techonerd/stock-assist, pull requests merged in 2022-10, with the labels that each got.

#7 create PR template
  .github/pull_request_template.md
Labels: documentation, enhancement

#8 create doc for getting started
  getting_started.md
Labels: documentation, good first issue

#9 contribution template fix
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
Labels: bug, documentation

#13 Search Feature
  .streamlit/config.toml
  app.py
  utils.py
Labels: enhancement

#25 CI Workflow development
  .github/workflows/ci.yml
  .github/workflows/stale.yml
Labels: enhancement
